fragment todo on Todo {
  id
  content
  active
  created_at
  updated_at
}

query myTodo($id: ID!) {
  myTodo(id: $id) {
    ...todo
  }
}

query myTodos($first: Int!, $page: Int!) {
  myTodos(
    first: $first
    page: $page
    orderBy: { column: CREATED_AT, order: DESC }
  ) {
    data {
      ...todo
    }
    paginatorInfo {
      count
      currentPage
      firstItem
      hasMorePages
      lastItem
      lastPage
      perPage
      total
    }
  }
}

mutation createTodo($content: String!) {
  createTodo(content: $content) {
    ...todo
  }
}

mutation updateTodo($id: ID!, $content: String, $active: Boolean) {
  updateTodo(id: $id, content: $content, active: $active) {
    ...todo
  }
}

mutation deleteTodo($id: ID!) {
  deleteTodo(id: $id) {
    ...todo
  }
}
